# Generated by Django 5.0 on 2023-12-13 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_time_alter_event_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
    ]
