# Generated by Django 5.0 on 2023-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_data",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
