# Generated by Django 5.0 on 2023-12-18 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_event_event_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_data",
        ),
    ]
